# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
---
- name: Create /etc/systemd/resolved.conf.d directory.
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Add DNS settings resolv.conf.
  ansible.builtin.template:
    src: templates/dns_servers.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_servers.conf
    owner: root
    group: root
    mode: '0644'
