# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
---
- hosts: all
  become: true
  gather_facts: true

  roles:
    - role: dns
    - role: hosts
    - role: swap
    - role: kubernetes-basics
    - role: kubernetes-master
