# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2
---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: dns
    - role: swap
    - role: hosts
    - role: kubernetes-basics
    - role: kubernetes-worker